[07/Aug/2014 11:00:21] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 36, in get
    result = in_import.import_new()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 49, in import_new
    return self.__import()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 37, in __import
    self.__process_response(response)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 28, in __process_response
    mail_import.import_msg()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 165, in import_msg
    self.__import_msg()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 139, in __import_msg
    self.__import_from_header()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 157, in __import_from_header
    self.mail.date = datetime.strptime(value[0:20].strip(), "%d %b %Y %X")
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data 'Tue, 5 Aug 2014 22:2' does not match format '%d %b %Y %X'
[07/Aug/2014 11:02:27] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 36, in get
    result = in_import.import_new()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 49, in import_new
    return self.__import()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 37, in __import
    self.__process_response(response)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 28, in __process_response
    mail_import.import_msg()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 166, in import_msg
    self.__import_msg()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 139, in __import_msg
    self.__import_from_header()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 158, in __import_from_header
    self.mail.date = datetime.strptime(value[0:20].strip(), "%d %b %Y %X")
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data 'Tue, 5 Aug 2014 22:2' does not match format '%d %b %Y %X'
[07/Aug/2014 11:03:45] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 36, in get
    result = in_import.import_new()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 49, in import_new
    return self.__import()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 37, in __import
    self.__process_response(response)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 28, in __process_response
    mail_import.import_msg()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 166, in import_msg
    self.__import_msg()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 139, in __import_msg
    self.__import_from_header()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 158, in __import_from_header
    self.mail.date = datetime.strptime(value[0:21].strip(), "%d %b %Y %X")
  File "/usr/lib/python2.7/_strptime.py", line 328, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains:  -
[07/Aug/2014 11:16:13] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 36, in get
    result = in_import.import_new()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 49, in import_new
    return self.__import()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 37, in __import
    self.__process_response(response)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 28, in __process_response
    mail_import.import_msg()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 166, in import_msg
    self.__import_msg()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 139, in __import_msg
    self.__import_from_header()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 155, in __import_from_header
    if value[0].isaplha():
AttributeError: 'unicode' object has no attribute 'isaplha'
[07/Aug/2014 11:18:15] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 36, in get
    result = in_import.import_new()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 49, in import_new
    return self.__import()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 37, in __import
    self.__process_response(response)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 28, in __process_response
    mail_import.import_msg()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 166, in import_msg
    self.__import_msg()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 139, in __import_msg
    self.__import_from_header()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 155, in __import_from_header
    if value[:1].isaplha():
AttributeError: 'unicode' object has no attribute 'isaplha'
[07/Aug/2014 11:18:33] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 36, in get
    result = in_import.import_new()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 49, in import_new
    return self.__import()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 37, in __import
    self.__process_response(response)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 28, in __process_response
    mail_import.import_msg()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 166, in import_msg
    self.__import_msg()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 139, in __import_msg
    self.__import_from_header()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 155, in __import_from_header
    if value[:1].isaplha():
AttributeError: 'unicode' object has no attribute 'isaplha'
[07/Aug/2014 13:02:24] WARNING [django.request:143] Not Found: /favicon.ico
[08/Aug/2014 05:11:20] WARNING [django.request:143] Not Found: /favicon.ico
[08/Aug/2014 09:26:29] WARNING [django.request:143] Not Found: /favicon.ico
[08/Aug/2014 10:07:17] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 35, in get
    in_import = InboxImport(user)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 17, in __init__
    self.service = Auth.get_gmail_srv(user)
  File "/home/lenovo/projects/contact/gmail/__init__.py", line 43, in get_gmail_srv
    return build('gmail', 'v1', http=http)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/apiclient/discovery.py", line 192, in build
    resp, content = http.request(requested_url)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/client.py", line 490, in new_request
    redirections, connection_type)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1263, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
ServerNotFoundError: Unable to find the server at www.googleapis.com
[08/Aug/2014 10:29:13] WARNING [django.request:143] Not Found: /favicon.ico
[08/Aug/2014 16:21:37] WARNING [django.request:143] Not Found: /favicon.ico
[08/Aug/2014 17:54:13] WARNING [django.request:143] Not Found: /favicon.ico
[10/Aug/2014 15:31:12] WARNING [django.request:143] Not Found: /favicon.ico
[10/Aug/2014 16:26:19] WARNING [django.request:143] Not Found: /favicon.ico
[11/Aug/2014 04:30:26] WARNING [django.request:143] Not Found: /favicon.ico
[11/Aug/2014 04:30:34] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 36, in get
    result = in_import.import_new()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 49, in import_new
    return self.__import()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 37, in __import
    self.__process_response(response)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 28, in __process_response
    mail_import.import_msg()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 167, in import_msg
    self.__import_msg()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 141, in __import_msg
    self.__import_from_header()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 159, in __import_from_header
    self.mail.date = datetime.strptime(value[0:20].strip(), "%d %b %Y %X")
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%d %b %Y %X'
[11/Aug/2014 04:43:14] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 35, in get
    in_import = InboxImport(user)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 17, in __init__
    self.service = Auth.get_gmail_srv(user)
  File "/home/lenovo/projects/contact/gmail/__init__.py", line 43, in get_gmail_srv
    return build('gmail', 'v1', http=http)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/apiclient/discovery.py", line 192, in build
    resp, content = http.request(requested_url)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/client.py", line 490, in new_request
    redirections, connection_type)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1257, in _conn_request
    conn.connect()
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1060, in connect
    raise socket.error, msg
error: [Errno 111] Connection refused
[11/Aug/2014 04:44:20] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 35, in get
    in_import = InboxImport(user)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 17, in __init__
    self.service = Auth.get_gmail_srv(user)
  File "/home/lenovo/projects/contact/gmail/__init__.py", line 43, in get_gmail_srv
    return build('gmail', 'v1', http=http)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/apiclient/discovery.py", line 192, in build
    resp, content = http.request(requested_url)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/client.py", line 490, in new_request
    redirections, connection_type)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1257, in _conn_request
    conn.connect()
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1060, in connect
    raise socket.error, msg
error: [Errno 111] Connection refused
[11/Aug/2014 04:47:13] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 35, in get
    in_import = InboxImport(user)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 17, in __init__
    self.service = Auth.get_gmail_srv(user)
  File "/home/lenovo/projects/contact/gmail/__init__.py", line 43, in get_gmail_srv
    return build('gmail', 'v1', http=http)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/apiclient/discovery.py", line 192, in build
    resp, content = http.request(requested_url)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/client.py", line 490, in new_request
    redirections, connection_type)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1257, in _conn_request
    conn.connect()
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1060, in connect
    raise socket.error, msg
error: [Errno 111] Connection refused
[11/Aug/2014 04:48:01] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 35, in get
    in_import = InboxImport(user)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 17, in __init__
    self.service = Auth.get_gmail_srv(user)
  File "/home/lenovo/projects/contact/gmail/__init__.py", line 43, in get_gmail_srv
    return build('gmail', 'v1', http=http)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/apiclient/discovery.py", line 192, in build
    resp, content = http.request(requested_url)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/client.py", line 490, in new_request
    redirections, connection_type)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1263, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
ServerNotFoundError: Unable to find the server at www.googleapis.com
[11/Aug/2014 04:48:44] WARNING [django.request:143] Not Found: /favicon.ico
[11/Aug/2014 04:48:46] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 35, in get
    in_import = InboxImport(user)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 17, in __init__
    self.service = Auth.get_gmail_srv(user)
  File "/home/lenovo/projects/contact/gmail/__init__.py", line 43, in get_gmail_srv
    return build('gmail', 'v1', http=http)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/apiclient/discovery.py", line 192, in build
    resp, content = http.request(requested_url)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/client.py", line 490, in new_request
    redirections, connection_type)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1257, in _conn_request
    conn.connect()
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1060, in connect
    raise socket.error, msg
error: [Errno 111] Connection refused
[11/Aug/2014 04:49:19] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 35, in get
    in_import = InboxImport(user)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 17, in __init__
    self.service = Auth.get_gmail_srv(user)
  File "/home/lenovo/projects/contact/gmail/__init__.py", line 43, in get_gmail_srv
    return build('gmail', 'v1', http=http)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/apiclient/discovery.py", line 192, in build
    resp, content = http.request(requested_url)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/client.py", line 490, in new_request
    redirections, connection_type)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1263, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
ServerNotFoundError: Unable to find the server at www.googleapis.com
[11/Aug/2014 04:50:11] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 35, in get
    in_import = InboxImport(user)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 17, in __init__
    self.service = Auth.get_gmail_srv(user)
  File "/home/lenovo/projects/contact/gmail/__init__.py", line 43, in get_gmail_srv
    return build('gmail', 'v1', http=http)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/apiclient/discovery.py", line 192, in build
    resp, content = http.request(requested_url)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/client.py", line 490, in new_request
    redirections, connection_type)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1257, in _conn_request
    conn.connect()
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1060, in connect
    raise socket.error, msg
error: [Errno 111] Connection refused
[11/Aug/2014 04:51:23] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 35, in get
    in_import = InboxImport(user)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 17, in __init__
    self.service = Auth.get_gmail_srv(user)
  File "/home/lenovo/projects/contact/gmail/__init__.py", line 43, in get_gmail_srv
    return build('gmail', 'v1', http=http)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/apiclient/discovery.py", line 192, in build
    resp, content = http.request(requested_url)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/client.py", line 490, in new_request
    redirections, connection_type)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1257, in _conn_request
    conn.connect()
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1060, in connect
    raise socket.error, msg
error: [Errno 111] Connection refused
[11/Aug/2014 04:57:47] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 35, in get
    in_import = InboxImport(user)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 17, in __init__
    self.service = Auth.get_gmail_srv(user)
  File "/home/lenovo/projects/contact/gmail/__init__.py", line 43, in get_gmail_srv
    return build('gmail', 'v1', http=http)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/apiclient/discovery.py", line 192, in build
    resp, content = http.request(requested_url)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/client.py", line 490, in new_request
    redirections, connection_type)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1257, in _conn_request
    conn.connect()
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1060, in connect
    raise socket.error, msg
error: [Errno 111] Connection refused
[11/Aug/2014 04:58:13] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 35, in get
    in_import = InboxImport(user)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 17, in __init__
    self.service = Auth.get_gmail_srv(user)
  File "/home/lenovo/projects/contact/gmail/__init__.py", line 43, in get_gmail_srv
    return build('gmail', 'v1', http=http)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/apiclient/discovery.py", line 192, in build
    resp, content = http.request(requested_url)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/client.py", line 490, in new_request
    redirections, connection_type)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1263, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
ServerNotFoundError: Unable to find the server at www.googleapis.com
[11/Aug/2014 05:09:10] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 35, in get
    in_import = InboxImport(user)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 17, in __init__
    self.service = Auth.get_gmail_srv(user)
  File "/home/lenovo/projects/contact/gmail/__init__.py", line 43, in get_gmail_srv
    return build('gmail', 'v1', http=http)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/apiclient/discovery.py", line 192, in build
    resp, content = http.request(requested_url)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/client.py", line 490, in new_request
    redirections, connection_type)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1257, in _conn_request
    conn.connect()
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1060, in connect
    raise socket.error, msg
error: [Errno 111] Connection refused
[11/Aug/2014 05:10:03] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 35, in get
    in_import = InboxImport(user)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 17, in __init__
    self.service = Auth.get_gmail_srv(user)
  File "/home/lenovo/projects/contact/gmail/__init__.py", line 43, in get_gmail_srv
    return build('gmail', 'v1', http=http)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/apiclient/discovery.py", line 192, in build
    resp, content = http.request(requested_url)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/client.py", line 490, in new_request
    redirections, connection_type)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1257, in _conn_request
    conn.connect()
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1060, in connect
    raise socket.error, msg
error: [Errno 111] Connection refused
[11/Aug/2014 05:11:12] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 35, in get
    in_import = InboxImport(user)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 17, in __init__
    self.service = Auth.get_gmail_srv(user)
  File "/home/lenovo/projects/contact/gmail/__init__.py", line 43, in get_gmail_srv
    return build('gmail', 'v1', http=http)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/apiclient/discovery.py", line 192, in build
    resp, content = http.request(requested_url)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/client.py", line 490, in new_request
    redirections, connection_type)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1257, in _conn_request
    conn.connect()
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1060, in connect
    raise socket.error, msg
error: [Errno 111] Connection refused
[11/Aug/2014 05:15:26] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 35, in get
    in_import = InboxImport(user)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 17, in __init__
    self.service = Auth.get_gmail_srv(user)
  File "/home/lenovo/projects/contact/gmail/__init__.py", line 43, in get_gmail_srv
    return build('gmail', 'v1', http=http)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/apiclient/discovery.py", line 192, in build
    resp, content = http.request(requested_url)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/client.py", line 490, in new_request
    redirections, connection_type)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1257, in _conn_request
    conn.connect()
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1060, in connect
    raise socket.error, msg
error: [Errno 111] Connection refused
[11/Aug/2014 05:16:35] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 35, in get
    in_import = InboxImport(user)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 17, in __init__
    self.service = Auth.get_gmail_srv(user)
  File "/home/lenovo/projects/contact/gmail/__init__.py", line 43, in get_gmail_srv
    return build('gmail', 'v1', http=http)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/apiclient/discovery.py", line 192, in build
    resp, content = http.request(requested_url)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/client.py", line 490, in new_request
    redirections, connection_type)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1257, in _conn_request
    conn.connect()
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1060, in connect
    raise socket.error, msg
error: [Errno 111] Connection refused
[11/Aug/2014 05:17:15] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 35, in get
    in_import = InboxImport(user)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 17, in __init__
    self.service = Auth.get_gmail_srv(user)
  File "/home/lenovo/projects/contact/gmail/__init__.py", line 43, in get_gmail_srv
    return build('gmail', 'v1', http=http)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/apiclient/discovery.py", line 192, in build
    resp, content = http.request(requested_url)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/client.py", line 490, in new_request
    redirections, connection_type)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1257, in _conn_request
    conn.connect()
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1060, in connect
    raise socket.error, msg
error: [Errno 111] Connection refused
[11/Aug/2014 05:18:29] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 35, in get
    in_import = InboxImport(user)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 17, in __init__
    self.service = Auth.get_gmail_srv(user)
  File "/home/lenovo/projects/contact/gmail/__init__.py", line 43, in get_gmail_srv
    return build('gmail', 'v1', http=http)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/apiclient/discovery.py", line 192, in build
    resp, content = http.request(requested_url)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/client.py", line 490, in new_request
    redirections, connection_type)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1257, in _conn_request
    conn.connect()
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1060, in connect
    raise socket.error, msg
error: [Errno 111] Connection refused
[11/Aug/2014 05:39:18] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 36, in get
    result = in_import.import_new()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 49, in import_new
    return self.__import()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 37, in __import
    self.__process_response(response)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 28, in __process_response
    mail_import.import_msg()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 167, in import_msg
    self.__import_msg()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 141, in __import_msg
    self.__import_from_header()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 159, in __import_from_header
    self.mail.date = datetime.strptime(value[0:20].strip(), "%d %b %Y %X")
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%d %b %Y %X'
[11/Aug/2014 05:39:46] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 36, in get
    result = in_import.import_new()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 49, in import_new
    return self.__import()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 37, in __import
    self.__process_response(response)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 28, in __process_response
    mail_import.import_msg()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 167, in import_msg
    self.__import_msg()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 141, in __import_msg
    self.__import_from_header()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 159, in __import_from_header
    self.mail.date = datetime.strptime(value[0:20].strip(), "%d %b %Y %X")
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%d %b %Y %X'
[11/Aug/2014 05:40:38] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 36, in get
    result = in_import.import_new()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 49, in import_new
    return self.__import()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 37, in __import
    self.__process_response(response)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 28, in __process_response
    mail_import.import_msg()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 167, in import_msg
    self.__import_msg()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 141, in __import_msg
    self.__import_from_header()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 159, in __import_from_header
    self.mail.date = datetime.strptime(value[0:20].strip(), "%d %b %Y %X")
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%d %b %Y %X'
[11/Aug/2014 05:41:50] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 36, in get
    result = in_import.import_new()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 49, in import_new
    return self.__import()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 37, in __import
    self.__process_response(response)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 28, in __process_response
    mail_import.import_msg()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 168, in import_msg
    self.__import_msg()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 141, in __import_msg
    self.__import_from_header()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 160, in __import_from_header
    self.mail.date = datetime.strptime(value[0:20].strip(), "%d %b %Y %X")
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%d %b %Y %X'
[11/Aug/2014 05:42:29] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 36, in get
    result = in_import.import_new()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 49, in import_new
    return self.__import()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 37, in __import
    self.__process_response(response)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 28, in __process_response
    mail_import.import_msg()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 169, in import_msg
    self.__import_msg()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 141, in __import_msg
    self.__import_from_header()
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 161, in __import_from_header
    self.mail.date = datetime.strptime(value[0:20].strip(), "%d %b %Y %X")
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%d %b %Y %X'
[11/Aug/2014 06:58:18] WARNING [django.request:143] Not Found: /contact/status/74/-5/
[11/Aug/2014 06:58:20] WARNING [django.request:143] Not Found: /contact/status/74/-5/
[11/Aug/2014 06:58:22] WARNING [django.request:143] Not Found: /contact/status/74/-5/
[11/Aug/2014 06:58:41] WARNING [django.request:143] Not Found: /contact/status/35/-5/
[11/Aug/2014 07:43:41] ERROR [django.request:224] Internal Server Error: /inbox/refresh/
Traceback (most recent call last):
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = self.handle_exception(exc)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/rest_framework/views.py", line 397, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/lenovo/projects/contact/gmail/views.py", line 35, in get
    in_import = InboxImport(user)
  File "/home/lenovo/projects/contact/gmail/parsers.py", line 17, in __init__
    self.service = Auth.get_gmail_srv(user)
  File "/home/lenovo/projects/contact/gmail/__init__.py", line 43, in get_gmail_srv
    return build('gmail', 'v1', http=http)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/apiclient/discovery.py", line 192, in build
    resp, content = http.request(requested_url)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/oauth2client/client.py", line 490, in new_request
    redirections, connection_type)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/lenovo/Envs/contact/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1263, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
ServerNotFoundError: Unable to find the server at www.googleapis.com
[11/Aug/2014 09:04:45] WARNING [django.request:143] Not Found: /lkdn/duplicates/undefined/
[11/Aug/2014 09:04:45] WARNING [django.request:143] Not Found: /contact/comm_items/undefined/
[11/Aug/2014 09:04:45] WARNING [django.request:143] Not Found: /contact/duplicates/undefined/
[11/Aug/2014 09:04:45] WARNING [django.request:143] Not Found: /contact/by_month/undefined/
[11/Aug/2014 09:06:11] WARNING [django.request:143] Not Found: /lkdn/duplicates/undefined/
[11/Aug/2014 09:06:11] WARNING [django.request:143] Not Found: /contact/comm_items/undefined/
[11/Aug/2014 09:06:11] WARNING [django.request:143] Not Found: /contact/duplicates/undefined/
[11/Aug/2014 09:06:11] WARNING [django.request:143] Not Found: /contact/by_month/undefined/
[11/Aug/2014 09:07:34] WARNING [django.request:143] Not Found: /contact/comm_items/undefined/
[11/Aug/2014 09:07:34] WARNING [django.request:143] Not Found: /contact/duplicates/undefined/
[11/Aug/2014 09:07:34] WARNING [django.request:143] Not Found: /lkdn/duplicates/undefined/
[11/Aug/2014 09:07:34] WARNING [django.request:143] Not Found: /contact/by_month/undefined/
[11/Aug/2014 09:10:43] WARNING [django.request:143] Not Found: /contact/status/undefined/20/
[11/Aug/2014 09:10:44] WARNING [django.request:143] Not Found: /contact/status/undefined/20/
[11/Aug/2014 09:10:46] WARNING [django.request:143] Not Found: /contact/status/undefined/20/
[11/Aug/2014 09:10:50] WARNING [django.request:143] Not Found: /contact/status/undefined/20/
[11/Aug/2014 09:10:51] WARNING [django.request:143] Not Found: /contact/status/undefined/20/
[11/Aug/2014 09:10:52] WARNING [django.request:143] Not Found: /contact/status/undefined/20/
[11/Aug/2014 09:18:20] WARNING [django.request:143] Not Found: /contact/duplicates/undefined/
[11/Aug/2014 09:18:20] WARNING [django.request:143] Not Found: /contact/by_month/undefined/
[11/Aug/2014 09:18:20] WARNING [django.request:143] Not Found: /lkdn/duplicates/undefined/
[11/Aug/2014 09:18:20] WARNING [django.request:143] Not Found: /contact/comm_items/undefined/
[11/Aug/2014 09:22:04] WARNING [django.request:143] Not Found: /lkdn/duplicates/undefined/
[11/Aug/2014 09:22:04] WARNING [django.request:143] Not Found: /contact/comm_items/undefined/
[11/Aug/2014 09:22:04] WARNING [django.request:143] Not Found: /contact/duplicates/undefined/
[11/Aug/2014 09:22:04] WARNING [django.request:143] Not Found: /contact/by_month/undefined/
[11/Aug/2014 09:45:44] WARNING [django.request:143] Not Found: /contact/status/8/undefined/
[11/Aug/2014 09:45:51] WARNING [django.request:143] Not Found: /contact/status/8/undefined/
[11/Aug/2014 09:46:15] WARNING [django.request:143] Not Found: /contact/status/22/undefined/
